backend = "glx";
vsync = true;
use-damage = true;
dithered-present = false;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

rules: (
  {
    # i3bar and the feh wallpaper: fading here just makes them flicker
    # when switching workspaces.
    match = "window_type = 'dock' || "
            "window_type = 'desktop'";
    fade = false;
  },
  { match = "class_g = 'Alacritty'"; opacity = 0.95 },
  {
    match = "class_g ?= 'dunst' || "
            "name = 'Notification'";
    fade = false;
  }
)
