[window]
opacity = 1
#opacity = 0.97

[font]
#normal = { family = "terminal-font", style = "Regular"}
size = 10.0
builtin_box_drawing = true

[cursor]
style = {shape = "Block", blinking = "On"}
blink_interval = 500
blink_timeout = 0

[colors.primary]
foreground = "#ffffff"
dim_foreground = "#ff0000"
bright_foreground = "#0000ff"
background = "#303030"

[colors.selection]
text = "#582265"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#aaaaaa"
green = "#aaaaaa"
yellow = "#aaaaaa"
blue = "#aaaaaa"
magenta = "#aaaaaa"
cyan = "#aaaaaa"
white = "#ffffff"

[colors.bright]
black = "#000000"
red = "#aaaaaa"
green = "#aaaaaa"
yellow = "#aaaaaa"
blue = "#aaaaaa"
magenta = "#aaaaaa"
cyan = "#aaaaaa"
white = "#ffffff"

[colors.dim]
black = "#000000"
red = "#aaaaaa"
green = "#aaaaaa"
yellow = "#aaaaaa"
blue = "#aaaaaa"
magenta = "#aaaaaa"
cyan = "#aaaaaa"
white = "#ffffff"

[colors.cursor]
text = "#101010"
cursor = "#ebe733"
